name: video_watermark
description: Simple Flutter package to add image as overlay in the video along with video trim option.
homepage: https://www.eded.in/video_watermark
repository: https://github.com/EDEDIN-Solutions/video_watermark
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.5

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
  path_provider: ^2.0.11

platforms:
  android:
  ios:
